Панов Антон Александрович ИТМО ДЗ №2
LargonG/kotlin-home-2 pull request #1
Opened 2023-01-22 13:03 UTC by LargonG

Добавил решения для heap, tree и flist

Из самодеятельности:
* Удалил возможность хранить в heap дерево значения null (потому что это бессмысленно, если у нас коллекция не может быть пустой)
* Добавил метод first() для FList, потому что это удобно. Если элемента нет, кидается ошибка NoSuchElementException

Из неприятного:
* Много if-ов в методе plus объекта внутри heap. Кажется, что от них избавиться нельзя, т.к. в основном эти if-ы проверяют, есть ли следующий элемент и вызываются РАЗНЫЕ алгоритмы после этого
* reverse() в BinomialTree нужен для того, чтобы соблюдать инвариант возрастания последовательности

2023-01-27 16:23 UTC, Kvel4 commented
По поводу как сделать оптимальнее не меняя логики хз, смотря что ты понимаешь под термином не меняя логики. В целом подход с 2 значениями + итераторами не очень. Видел реализацию plus в 20-30 строк, если интересно могу поискать

2023-01-27 16:23 UTC, Kvel4 requested changes

2023-01-27 16:23 UTC, Kvel4 commented on lib/src/main/kotlin/binomial/FList.kt
> +private fun <T> flistOf(values: Array<out T>, index: Int): FList<T> {
StackOverflow на 10^5. Так же и для map, filter, fold

2023-01-27 16:24 UTC, Kvel4 commented
Поправь стек оверфлоу, и зачту таску, в остальном кроме plus мне все понравилось

2023-01-27 17:41 UTC, Kvel4 commented
Ты только сейчас сделал таску или есть ссылка на старый коммит?

2023-01-27 18:01 UTC, LargonG commented
> Ты только сейчас сделал таску или есть ссылка на старый коммит?

Да, только сейчас (5 дней назад)

2023-01-28 15:57 UTC, Kvel4 approved these changes

2023-01-28 15:58 UTC, merged